### ISSUE TITLE
Use u32 as input for PCF8575 instead of u16

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [eldruin/pcf857x-rs#3]
PCF8575 has 18 output pins, so u16 doesn't have enough bits for that. A workaround is to set through an array, but it's just a workaround.

**Comment by eldruin** [comment]
You may be confused about the numbering of the pins. They are called P00-P07 and P10-P17 but there is still only 16 output pins (notice the missing P08, P09).
See the [datasheet](https://www.nxp.com/docs/en/data-sheet/PCF8575.pdf)
If I understood you wrong please feel free to reopen this.
